name: CD (prod env)

# 触发workflow的条件
on:
  workflow_call:
    secrets:
      TARGET_SERVERS:
        required: true
      CDN_REFRESH_API_SID:
        required: true
      CDN_REFRESH_API_SKEY:
        required: true
      PI:
        required: false
      COS_API_ID:
        required: true
      COS_API_KEY:
        required: true
      COS_API_BUCKET:
        required: true

jobs:

  # 输出目标服务器名称组成的矩阵
  # 问就是Github不给传机密，所以只能传索引
  eval-targets-names-matricies:
    runs-on: ubuntu-latest
    outputs:
      matricies: ${{ steps.eval.outputs.result }}
    steps:
      - name: Write secret to file
        run: mkdir ./.github && echo '${{ secrets.TARGET_SERVERS }}' > ./.github/target-servers.yml
      - name: Eval targets names
        id: eval
        uses: mikefarah/yq@master
        with:
          cmd: |-
            yq -o=json -I=0 eval 'map_values(map(.name))' ./.github/target-servers.yml
          # Reference: https://mikefarah.gitbook.io/yq/usage/convert#encode-json-simple-in-one-line\


  deploy:
    needs: eval-targets-names-matricies
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      type: prod
    strategy:
      matrix:
        target-name: ${{fromJson(needs.eval-targets-names-matricies.outputs.matricies).prod}}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - id: sanitize_artifact_name
        uses: ./.github/actions/sanitize-name
        with:
          name: ${{ github.ref_name }}

      # 下载Flutter构建产物
      - name: 'Download Build Artifacts - ${{ github.ref_name }} - Flutter'
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.sanitize_artifact_name.outputs.sanitized_name }}-build-flutter
          path: dist/flutter_project/build/web/

      # 下载Vue构建产物
      - name: 'Download Build Artifacts - ${{ github.ref_name }} Vue'
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.sanitize_artifact_name.outputs.sanitized_name }}-build-vue
          path: dist/vue/dist/
      
      # 获取服务器信息
      - name: Write targets secret to file
        run: echo '${{ secrets.TARGET_SERVERS }}' > ./.github/target-servers.yml
      - name: Get target info
        id: get-target-info
        uses: mikefarah/yq@master
        with:
            cmd: |-
              yq -o=json -I=0 eval '.${{ env.type }}.[] | select(.name == "${{ matrix.target-name }}")' ./.github/target-servers.yml

      # 部署到服务器
      - name: Incremental Deploy to ${{ fromJSON(steps.get-target-info.outputs.result).name }}
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ fromJSON(steps.get-target-info.outputs.result).privateKey }}
          REMOTE_HOST: ${{ fromJSON(steps.get-target-info.outputs.result).host }}
          REMOTE_PORT: ${{ fromJSON(steps.get-target-info.outputs.result).port }}
          REMOTE_USER: ${{ fromJSON(steps.get-target-info.outputs.result).username }}
          ARGS: '-avz --delete'
          # https://ss64.com/bash/rsync_options.html
          SOURCE: 'dist/'
          TARGET: ${{ fromJSON(steps.get-target-info.outputs.result).dstPath }} # 服务器目标路径

  upload-cdn:
    needs: deploy
    uses: ./.github/workflows/cd-upload-cdn.yml
    secrets: inherit
    with:
      cospath: 'prod/'

  # 刷新eo
  refresh-eo:
    needs: deploy
    uses: ./.github/workflows/cd-refresh-eo.yml
    secrets: inherit