# The workflow to execute the CD process for a existing Github Environment specified by the job input parameter.
# The workflow accesses the secrets in the Environments to get the information for the deployment.

name: CD for a specific Environment

on:
  workflow_call:
    inputs:
      environment:
        description: "The name of the Github Environment to deploy to"
        type: string
        required: true
        default: dev
    secrets:
      SSH_DEPLOY_KEY:
        required: true
      EO_API_SID:
        required: true
      EO_API_SKEY:
        required: true
      COS_API_ID:
        required: true
      COS_API_KEY:
        required: true
      COS_API_BUCKET:
        required: true

jobs:
  ssh-deploy:
    uses: ./.github/workflows/cd-ssh-deploy.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}

  # 上传CDN
  upload-cdn:
    needs: ssh-deploy
    uses: ./.github/workflows/cd-upload-cdn.yml
    secrets: inherit
    with:
      cospath: ${{ inputs.environment }}/

  # 刷新eo（条件：environment == 'prod'）
  refresh-eo:
    needs: ssh-deploy
    if: ${{ inputs.environment == 'prod' }}
    uses: ./.github/workflows/cd-refresh-eo.yml
    secrets: inherit