name: CD

on:
  workflow_call:
    secrets:
      # for ssh deploy
      SSH_DEPLOY_KEY:
        required: true
      # for Tencent Edgeone refresh API
      EO_API_SID:
        required: true
      EO_API_SKEY:
        required: true
      # for the CDN on Tencent COS
      COS_API_ID:
        required: true
      COS_API_KEY:
        required: true
      COS_API_BUCKET:
        required: true
      # test
      PI:
        required: false


jobs:
  
  cd-dev:
    uses: ./.github/workflows/cd-to-env.yml
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/workflow-dev'
    with:
        environment: dev
    secrets: inherit

  cd-prod:
    uses: ./.github/workflows/cd-to-env.yml
    if: github.ref == 'refs/heads/main'
    with:
        environment: prod
    secrets: inherit