name: CD

on:
  workflow_call:
    inputs:
      ENV_TYPE:
        description: "The Environment to deploy"
        type: string
        required: true
      sha:
        description: "The specified commit's sha"
        type: string
        required: false
    secrets:
      # for ssh deploy
      SSH_DEPLOY_KEY:
        required: true
      # for Tencent Edgeone refresh API
      EO_API_SID:
        required: true
      EO_API_SKEY:
        required: true
      # for the CDN on Tencent COS
      COS_API_ID:
        required: true
      COS_API_KEY:
        required: true
      COS_API_BUCKET:
        required: true
      # test
      PI:
        required: false

jobs:
  ssh-deploy:
    uses: ./.github/workflows/cd-ssh-deploy.yml
    with:
      ENV_TYPE: ${{ inputs.ENV_TYPE }}
      sha: ${{ inputs.sha }}
    secrets: inherit

  # 上传CDN
  upload-cdn:
    needs: ssh-deploy
    uses: ./.github/workflows/cd-upload-cdn.yml
    secrets: inherit
    with:
      cospath: "${{ inputs.ENV_TYPE }}/"
      sha: ${{ inputs.sha }}

  # 刷新eo（条件：environment == 'prod'）
  refresh-eo:
    needs: ssh-deploy
    if: ${{ inputs.ENV_TYPE == 'prod' }}
    uses: ./.github/workflows/cd-refresh-eo.yml
    secrets: inherit
