name: CI - Build Vue Project

# 触发workflow的条件
on:
    workflow_call:
        inputs:
            dir:
                required: true
                type: string
                description: 'Vue Project Directory'

jobs:
    # 构建Vue项目任务
    build-vue:
        runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
        
        defaults:
            run:
                shell: bash
                working-directory: ${{ inputs.dir }}

        steps:
            - name: Checkout code
              uses: actions/checkout@master
              with:
                  ref: ${{ github.ref }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                check-latest: true
            
            - name: Setup pnpm & dependencies
              run: |
                npm install -g pnpm
                pnpm install
            
            - name: Lint Vue Project
              run: pnpm lint
            
            - name: Config (dev)
              if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/workflow-dev'
              run: 'echo \x22{"aegis_env": "dev"}\x22 > config.json'
            
            - name: Config (prod)
              if: github.ref == 'refs/heads/main'
              run: 'echo \x22{"aegis_env": "prod"}\x22 > config.json'
            
            - name: Build Vue Project
              run: pnpm build

            - id: sanitize_artifact_name
              uses: ./.github/actions/sanitize-name
              with:
                name: ${{ github.ref_name }}
                  
            - name: 'Upload Build Artifacts - ${{ github.ref_name }} - Vue'
              if: steps.sanitize_artifact_name.outputs.sanitized_name
              uses: actions/upload-artifact@v4
              with:
                name: ${{ steps.sanitize_artifact_name.outputs.sanitized_name }}-build-vue
                path: ${{ inputs.dir }}/dist