name: CI - Build Vue Project

# 触发workflow的条件
on:
    workflow_call:
        inputs:
            dir:
                required: true
                type: string
                description: 'Vue Project Directory'
            ENV_TYPE: 
                description: 'The Environment to deploy'
                type: string
                required: true

jobs:
    # 构建Vue项目任务
    build-vue:
        runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
        
        defaults:
            run:
                shell: bash
                working-directory: ${{ inputs.dir }}

        steps:
            - name: Checkout code
              uses: actions/checkout@master
              with:
                  ref: ${{ github.ref }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                check-latest: true
            
            - name: Setup pnpm & dependencies
              run: |
                npm install -g pnpm
                pnpm install
            
            - name: Lint Vue Project
              run: pnpm lint
            
            - name: Config (${{ inputs.ENV_TYPE }})
              run: |
                  echo '{"aegis_env": "${{ inputs.ENV_TYPE }}"}' > config.json
            
            - name: Build Vue Project
              run: pnpm build
            
            - name: 'Upload Build Artifacts - ${{ github.sha }} - Vue'
              uses: actions/upload-artifact@v4
              with:
                name: ${{ github.sha }}-build-vue
                path: ${{ inputs.dir }}/dist