name: Main Workflow - When PR to main branch updates
on:
    pull_request_target:
        branches: [main]

jobs:
    ci:
        uses: ./.github/workflows/ci.yml
        with:
            ENV_TYPE: dev
    
    cd:
        needs: ci
        uses: ./.github/workflows/cd.yml
        with:
            ENV_TYPE: dev
        secrets: inherit